# Generated by Django 5.1.5 on 2025-01-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('agent_ip', models.CharField(max_length=15)),
                ('agent_port', models.IntegerField()),
                ('data_count', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Packets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('src_ip', models.CharField(max_length=15)),
                ('dst_ip', models.CharField(max_length=15)),
                ('src_mac', models.CharField(max_length=17)),
                ('dst_mac', models.CharField(max_length=17)),
                ('src_port', models.IntegerField()),
                ('dst_port', models.IntegerField()),
                ('data', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
