# Generated by Django 5.1.5 on 2025-01-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agents',
            name='agent_last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
