# Generated by Django 5.1.5 on 2025-01-22 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_apr_mitm_delete_packets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agents',
            name='agent_port',
        ),
    ]
